"""add website, genres to venues and artists

Revision ID: 080b39c05bab
Revises: 11d9bce76bac
Create Date: 2020-09-17 02:39:07.464630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '080b39c05bab'
down_revision = '11d9bce76bac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('website', sa.String(length=120), nullable=True))
    op.add_column('venue', sa.Column('genres', sa.String(length=120), nullable=True))
    op.add_column('venue', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'website')
    op.drop_column('venue', 'genres')
    op.drop_column('artist', 'website')
    # ### end Alembic commands ###
