"""add upcoming to show

Revision ID: 7e4c055f73ad
Revises: a42ffa275a0d
Create Date: 2020-09-18 23:48:06.985695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e4c055f73ad'
down_revision = 'a42ffa275a0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('upcoming', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'upcoming')
    # ### end Alembic commands ###
