"""adding columns venue artist

Revision ID: c93fba2ae6b4
Revises: 080b39c05bab
Create Date: 2020-09-18 21:05:06.710226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c93fba2ae6b4'
down_revision = '080b39c05bab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('past_shows_count', sa.Integer(), nullable=True))
    op.add_column('artist', sa.Column('seeking_description', sa.Text(), nullable=True))
    op.add_column('artist', sa.Column('upcoming_shows_count', sa.Integer(), nullable=True))
    op.add_column('venue', sa.Column('past_shows_count', sa.Integer(), nullable=True))
    op.add_column('venue', sa.Column('seeking_description', sa.Text(), nullable=True))
    op.add_column('venue', sa.Column('upcoming_shows_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'upcoming_shows_count')
    op.drop_column('venue', 'seeking_description')
    op.drop_column('venue', 'past_shows_count')
    op.drop_column('artist', 'upcoming_shows_count')
    op.drop_column('artist', 'seeking_description')
    op.drop_column('artist', 'past_shows_count')
    # ### end Alembic commands ###
